# StandardId configuration
# Generated by: rails g standard_id:install

StandardId.configure do |c|
  # Base configuration (account model, infrastructure settings)
  c.account_class_name = "User"
  # c.cache_store = Rails.cache
  # c.logger = Rails.logger
  # c.web_layout = "application"
  # c.passwordless_email_sender = ->(email, code) { PasswordlessMailer.with(code: code, to: email).deliver_later }
  # c.passwordless_sms_sender   = ->(phone, code) { SmsProvider.send_code(phone: phone, code: code) }

  # Configuration subsets (creates static OpenStruct objects)
  # c.passwordless.code_ttl = 600 # 10 minutes
  # c.passwordless.max_attempts = 3
  # c.password.minimum_length = 8
  # c.password.require_special_chars = true
  # c.oauth.default_token_lifetime = 3600 # 1 hour
  # c.oauth.refresh_token_lifetime = 2_592_000 # 30 days
  # c.oauth.token_lifetimes = {
  #   password: 8.hours,
  #   client_credentials: 24.hours
  # }
  # c.oauth.scope_claims = {
  #   profile: %i[email display_name]
  # }
  # c.oauth.claim_resolvers = {
  #   email: ->(account:) { account.email },
  #   display_name: ->(account:, client:) {
  #     "#{account.name} for #{client.client_id}"
  #   }
  # }

  # Social login credentials (if enabled in your app)
  # c.social.google_client_id     = ENV["GOOGLE_CLIENT_ID"]
  # c.social.google_client_secret = ENV["GOOGLE_CLIENT_SECRET"]
  # c.social.apple_client_id      = ENV["APPLE_CLIENT_ID"]
  # c.social.apple_private_key    = ENV["APPLE_PRIVATE_KEY"]
  # c.social.apple_key_id         = ENV["APPLE_KEY_ID"]
  # c.social.apple_team_id        = ENV["APPLE_TEAM_ID"]

  # OIDC Logout allow list
  # c.allowed_post_logout_redirect_uris = [
  #   "https://app.example.com/logged_out",
  #   "https://admin.example.com/signout"
  # ]
end

# Notes:
# - All configuration scopes and fields are defined via the schema DSL
#   in: lib/standard_id/config/schema.rb
# - Values are automatically cast to the correct type (string, integer, boolean, etc.)
# - Invalid scopes or fields will raise ArgumentError with helpful messages
