version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "*"
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
