# StandardId configuration
# Generated by: rails g standard_id:install

StandardId.configure do |c|
  # Set to the String name of your account model (e.g., "User" or "Account")
  c.account_class_name = "Account"

  # Optional: customize cache store and logger used internally by StandardId
  # c.cache_store = Rails.cache
  # c.logger = Rails.logger
end
